### ISSUE TITLE
Historia de Usuário 

### ISSUE THREAD

**Issue by MatheuZAguiar** [grupo-08-projeto-integrador/backend#2]
Lucas estava com o problema de divulgação do produto com o cliente, onde ele sempre tinha que enviar fotos de todo o catalogo por mídias sociais.
Lucas quer um site que mostre o catalogo da loja de roupas onde trabalha, onde que seus produtos fiquem expostos em Vitrines Digitais onde os principais objetivos sejam expor o produto, mostrar o valor e divulgar.
Lucas quer que o usuário possa criar uma conta no site que tenha cadastro de usuário, onde o usuário poderá deixar seus produtos no carrinho para encaminhar para um atendimento online humanizado, um atendente irá resolver o método de pagamento e confirmar o endereço de entrega do usuário.

[Historia_de_Usuario.docx](https://github.com/grupo-08-projeto-integrador/backend/files/11456757/Historia_de_Usuario.docx)

**Comment by ferreiraluc** [comment]
Historia de usuario adicionada no README do git. 

![image](https://github.com/grupo-08-projeto-integrador/backend/assets/70459562/7a4ca7bb-e949-4f33-acd8-f0e88eaa8f3a)
